file = open("myfile.txt","w")
file.write("Name : Ariho\n")
file.write("Contact : +256751659154\n")
file.write("Location : Kampala\n")
file.close()
file = open("myfile.txt","r")
content = file.read()
print(content)
file.close()
# Read the file
file = open("myfile.txt","w")
file.write("Tedros\n")
file.write("Milka")
file.close()
file = open("myfile.txt","r")
content = file.read()
print(content)
file.close()
file = open("myfile.txt","r")
print(file.readline())
file.close()
