file = open("myfile.txt","w")
file.write("Name : Ariho\n")
file.write("Contact : +256751659154\n")
file.write("Location : Kampala\n")
file.close()
file = open("myfile.txt","r")
content = file.read()
print(content)
file.close()